apiVersion: apps/v1
kind: Deployment

metadata:
  name: inventory-api

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: inventory-api

  template:

    metadata:
      labels:
        app: inventory-api

    spec:

      containers:
      - name: inventory-api

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8000

        livenessProbe:
          httpGet:
            path: /health
            port: 8000

        readinessProbe:
          httpGet:
            path: /health
            port: 8000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
